#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 9/13/16 2:29 PM
# @Author  : Runsheng
# @Email   : Runsheng.lee@gmail.com
# @File    : utils.py

"""
Some general functions used for sequence file parser and coding running
"""

# Third oart import
from Bio import SeqIO




def fasta2dic(fastafile):
    """
    Give a fasta file name, return a dict contains the name and seq
    Require Biopython SeqIO medule to parse the sequence into dict, a large genome may take a lot of RAM
    """
    handle=open(fastafile, "rU")
    record_dict=SeqIO.to_dict(SeqIO.parse(handle,"fasta"))
    handle.close()
    return record_dict


def dic2dic(record_dict):
    """
    :param record_dict: a SeqIO dict generated by Biopython
    :return the dict contain {name:seq}
    """
    seq_dict={}
    for k,v in record_dict.iteritems():
        seq=str(v.seq)
        seq_dict[k]=seq.upper()
    return seq_dict


def chr_select(seq_dict, chro, start,end):
    """
    Note the start and end is 0 based
    give the name of refdic, and the chr, start and end to be used
    return the name and sequence
    for example, chrcut(record_dict, "I", 100,109) returns
     ("I:100_109","AAAAAAAAAA")
    """
    name=chro+ ":"+str(round(float(start)/1000000,2))+"M"
    seq=str(seq_dict[chro])[start:end]
    return name,seq